// @ts-check
import eslint from '@eslint/js'
import eslintConfigPrettier from 'eslint-config-prettier'
import simpleImportSort from 'eslint-plugin-simple-import-sort'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default [
    {
        ignores: ['eslint.config.mjs', 'dist/**', 'node_modules/**', 'coverage/**', 'generated/**'],
    },
    eslint.configs.recommended,
    ...tseslint.configs.recommendedTypeChecked,
    {
        languageOptions: {
            parserOptions: {
                project: true,
                tsconfigRootDir: import.meta.dirname,
            },
            globals: {
                ...globals.node,
                ...globals.jest,
            },
        },
    },
    {
        plugins: {
            'simple-import-sort': simpleImportSort,
        },
        rules: {
            '@typescript-eslint/no-explicit-any': 'off',
            '@typescript-eslint/no-floating-promises': 'error',
            '@typescript-eslint/no-unsafe-argument': 'error',
            '@typescript-eslint/require-await': 'error',
            '@typescript-eslint/promise-function-async': 'error',
            '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
            '@typescript-eslint/prefer-readonly': 'error',
            '@typescript-eslint/no-inferrable-types': 'off',
            '@typescript-eslint/ban-ts-comment': 'warn',
            '@typescript-eslint/no-non-null-assertion': 'warn',
            '@typescript-eslint/prefer-nullish-coalescing': 'error',
            '@typescript-eslint/prefer-optional-chain': 'error',
            '@typescript-eslint/no-unnecessary-condition': 'warn',
            '@typescript-eslint/no-unnecessary-type-assertion': 'error',
            // Устаревшее правило, заменено на prefer-readonly
            // '@typescript-eslint/prefer-const': 'error',
            '@typescript-eslint/prefer-as-const': 'error',
            '@typescript-eslint/prefer-for-of': 'warn',
            '@typescript-eslint/prefer-includes': 'error',
            '@typescript-eslint/prefer-string-starts-ends-with': 'error',
            '@typescript-eslint/require-array-sort-compare': 'warn',
            '@typescript-eslint/unbound-method': 'error',
            'simple-import-sort/imports': 'error',
            'simple-import-sort/exports': 'error',
            // Правила для форматирования и отступов
            'padding-line-between-statements': [
                'error',
                { blankLine: 'always', prev: 'multiline-block-like', next: '*' },
                { blankLine: 'always', prev: 'multiline-expression', next: '*' },
                { blankLine: 'always', prev: 'multiline-const', next: '*' },
                { blankLine: 'always', prev: 'multiline-let', next: '*' },
                { blankLine: 'always', prev: 'multiline-var', next: '*' },
                { blankLine: 'always', prev: 'export', next: '*' },
                { blankLine: 'always', prev: 'import', next: '*' },
                { blankLine: 'any', prev: 'import', next: 'import' },
                { blankLine: 'any', prev: 'export', next: 'export' },
                { blankLine: 'always', prev: 'block-like', next: '*' },
                { blankLine: 'always', prev: 'class', next: '*' },
                { blankLine: 'always', prev: '*', next: 'class' },
                { blankLine: 'always', prev: 'function', next: '*' },
                { blankLine: 'always', prev: '*', next: 'function' },
                // Отступы внутри функций между логическими блоками
                { blankLine: 'always', prev: 'if', next: '*' },
                { blankLine: 'always', prev: '*', next: 'if' },
                { blankLine: 'always', prev: 'for', next: '*' },
                { blankLine: 'always', prev: '*', next: 'for' },
                { blankLine: 'always', prev: 'while', next: '*' },
                { blankLine: 'always', prev: '*', next: 'while' },
                { blankLine: 'always', prev: 'switch', next: '*' },
                { blankLine: 'always', prev: '*', next: 'switch' },
                { blankLine: 'always', prev: 'try', next: '*' },
                { blankLine: 'always', prev: '*', next: 'try' },
                { blankLine: 'always', prev: 'return', next: '*' },
                { blankLine: 'always', prev: 'throw', next: '*' },
                { blankLine: 'always', prev: 'break', next: '*' },
                { blankLine: 'always', prev: 'continue', next: '*' },
                { blankLine: 'always', prev: 'block', next: '*' },
                { blankLine: 'always', prev: '*', next: 'block' },
                { blankLine: 'always', prev: 'multiline-block-like', next: 'multiline-block-like' },
            ],
            // Дополнительные правила для улучшения читаемости
            'lines-between-class-members': ['error', 'always'],
            'newline-per-chained-call': ['error', { ignoreChainWithDepth: 4 }],
            'no-multiple-empty-lines': ['error', { max: 2, maxEOF: 1 }],
            'object-curly-spacing': ['error', 'always'],
            'array-bracket-spacing': ['error', 'never'],
            'comma-spacing': ['error', { before: false, after: true }],
            'key-spacing': ['error', { beforeColon: false, afterColon: true }],
            'space-before-function-paren': [
                'error',
                {
                    anonymous: 'never',
                    named: 'never',
                    asyncArrow: 'always',
                },
            ],
            'keyword-spacing': ['error', { before: true, after: true }],
            'space-infix-ops': 'error',
            'eol-last': ['error', 'always'],
            // Правила для форматирования внутри функций
            'brace-style': ['error', '1tbs', { allowSingleLine: true }],
            curly: ['error', 'all'],
            indent: ['error', 4, { SwitchCase: 1 }],
            'max-depth': ['warn', 4],
            'max-nested-callbacks': ['warn', 3],
            'max-len': ['error', { code: 100, ignoreUrls: true }],
            'max-statements-per-line': ['error', { max: 1 }],
            'no-trailing-spaces': 'error',
            'padded-blocks': ['error', 'never'],
            'space-before-blocks': 'error',
            'space-in-parens': 'error',
            'spaced-comment': ['error', 'always'],
            // Дополнительные правила для улучшения качества кода
            'array-callback-return': 'error',
            'consistent-return': 'error',
            'default-case': 'error',
            'dot-notation': 'error',
            eqeqeq: ['error', 'always'],
            'no-alert': 'error',
            'no-caller': 'error',
            'no-console': 'warn',
            'no-debugger': 'error',
            'no-eval': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-implied-eval': 'error',
            'no-iterator': 'error',
            'no-labels': 'error',
            'no-lone-blocks': 'error',
            'no-loop-func': 'error',
            'no-magic-numbers': ['warn', { ignore: [-1, 0, 1, 2] }],
            'no-multi-spaces': 'error',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-octal-escape': 'error',
            'no-param-reassign': 'warn',
            'no-proto': 'error',
            'no-redeclare': 'error',
            'no-return-assign': 'error',
            'no-self-compare': 'error',
            'no-sequences': 'error',
            'no-throw-literal': 'error',
            'no-unmodified-loop-condition': 'error',
            'no-unused-expressions': 'error',
            'no-useless-call': 'error',
            'no-useless-concat': 'error',
            'no-void': 'error',
            'no-with': 'error',
            'prefer-promise-reject-errors': 'error',
            radix: 'error',
            'require-await': 'error',
            yoda: 'error',
        },
    },
    eslintConfigPrettier,
]
