import type { Contact } from '@/types'

export const contacts: Contact[] = [
    { name: 'Mämmedow Döwlet', avatar: '/avatars/1.png', status: 'online' },
    { name: 'Orazowa Jeren', avatar: '/avatars/2.png', status: 'offline' },
    { name: 'Gurbanow Batyr', avatar: '/avatars/3.png', status: 'online' },
    { name: 'Ataýewa Maral', avatar: '/avatars/4.png', status: 'online' },
    { name: 'Berdiýew Serdar', avatar: '/avatars/5.png', status: 'offline' },
    { name: 'Saparowa Aýlar', avatar: '/avatars/6.png', status: 'online' },
    { name: 'Jumaýew Merdan', avatar: '/avatars/7.png', status: 'online' },
    { name: 'Nuryýewa Leýli', avatar: '/avatars/8.png', status: 'offline' },
    { name: 'Kerimow Maksat', avatar: '/avatars/9.png', status: 'online' },
    { name: 'Geldiýewa Jennet', avatar: '/avatars/10.png', status: 'online' },
    { name: 'Annaýew Arslan', avatar: '/avatars/11.png', status: 'offline' },
    { name: 'Durdyýewa Mahym', avatar: '/avatars/12.png', status: 'online' },
    { name: 'Hojaýew Begenç', avatar: '/avatars/13.png', status: 'online' },
    { name: 'Aşyrowa Gunça', avatar: '/avatars/14.png', status: 'offline' },
    { name: 'Rejepow Azat', avatar: '/avatars/15.png', status: 'online' },
    { name: 'Tekaýewa Bahar', avatar: '/avatars/16.png', status: 'online' },
    { name: 'Hudaýberdiýew Rustam', avatar: '/avatars/17.png', status: 'offline' },
    { name: 'Garryýewa Şirin', avatar: '/avatars/18.png', status: 'online' },
    { name: 'Soltanow Mekan', avatar: '/avatars/19.png', status: 'online' },
    { name: 'Baýramowa Selbi', avatar: '/avatars/20.png', status: 'offline' },
    { name: 'Esenow Toýly', avatar: '/avatars/21.png', status: 'online' },
    { name: 'Nazarowa Maýa', avatar: '/avatars/22.png', status: 'online' },
    { name: 'Şukurow Aman', avatar: '/avatars/23.png', status: 'offline' },
    { name: 'Guliyewa Jahan', avatar: '/avatars/24.png', status: 'online' },
    { name: 'Rahmanow Sohbet', avatar: '/avatars/25.png', status: 'online' },
    { name: 'Kakabaýewa Ogulnabat', avatar: '/avatars/26.png', status: 'offline' },
    { name: 'Çaryýew Didar', avatar: '/avatars/27.png', status: 'online' },
    { name: 'Ýusupowa Aýna', avatar: '/avatars/28.png', status: 'online' },
    { name: 'Seýidow Rowshen', avatar: '/avatars/29.png', status: 'offline' },
    { name: 'Bazarowa Gülşat', avatar: '/avatars/30.png', status: 'online' },
    { name: 'Hudaýberdiýew Allaberdi', avatar: '/avatars/31.png', status: 'online' },
    { name: 'Gurbannazarowa Bibigözel', avatar: '/avatars/32.png', status: 'offline' },
    { name: 'Mämmetnazarow Muhammetnazar', avatar: '/avatars/33.png', status: 'online' },
    { name: 'Annaorazowa Merjenjemal', avatar: '/avatars/34.png', status: 'online' },
    { name: 'Saparmuhammedow Abdurahman', avatar: '/avatars/35.png', status: 'offline' },
    { name: 'Berdimuhammedowa Ogulgerek', avatar: '/avatars/36.png', status: 'online' },
    { name: 'Ataýewmuhammedow Nurmuhammet', avatar: '/avatars/37.png', status: 'online' },
    { name: 'Baýramgeldiýewa Gülşatjemal', avatar: '/avatars/38.png', status: 'offline' },
    { name: 'Döwletmuhammedow Sylapberdi', avatar: '/avatars/39.png', status: 'online' },
    { name: 'Annamuhammedowa Tavusbibi', avatar: '/avatars/40.png', status: 'online' },
    { name: 'Rejepmuhammedow Guwançberdi', avatar: '/avatars/41.png', status: 'offline' },
    { name: 'Täçmuhammedowa Ogulbagt', avatar: '/avatars/42.png', status: 'online' },
    { name: 'Hojamuhammedow Aşyrmuhammet', avatar: '/avatars/43.png', status: 'online' },
    { name: 'Gurbanberdiýewa Ejegözel', avatar: '/avatars/44.png', status: 'offline' },
    { name: 'Amanmuhammedow Hydyrberdi', avatar: '/avatars/45.png', status: 'online' },
    { name: 'Babaorazowa Merjenbibi', avatar: '/avatars/46.png', status: 'online' },
    { name: 'Allaberdiýew Myratberdi', avatar: '/avatars/47.png', status: 'offline' },
    { name: 'Sarymuhammedowa Oguljahan', avatar: '/avatars/48.png', status: 'online' },
    { name: 'Gurbangeldiýew Muhammetali', avatar: '/avatars/49.png', status: 'online' },
    { name: 'Ýagşymuhammedowa Aýjemal', avatar: '/avatars/50.png', status: 'offline' },
    { name: 'Garrymuhammedow Hudaýberdi', avatar: '/avatars/51.png', status: 'online' },
    { name: 'Gurbanmyradowa Tyllagözel', avatar: '/avatars/52.png', status: 'online' },
    { name: 'Hydyrmuhammedow Saparmuhammet', avatar: '/avatars/53.png', status: 'offline' },
    { name: 'Mämmetgeldiýewa Güljahan', avatar: '/avatars/54.png', status: 'online' },
    { name: 'Nazarberdiýew Orazmuhammet', avatar: '/avatars/55.png', status: 'online' },
    { name: 'Jumamuhammedowa Bossangözel', avatar: '/avatars/56.png', status: 'offline' },
    { name: 'Atamuhammedow Berdimyrat', avatar: '/avatars/57.png', status: 'online' },
    { name: 'Döwletgeldiýewa Ogulşat', avatar: '/avatars/58.png', status: 'online' },
    { name: 'Rahmangulyýew Muhammetberdi', avatar: '/avatars/59.png', status: 'offline' },
    { name: 'Halmuhammedowa Enejanbibi', avatar: '/avatars/60.png', status: 'online' },
    { name: 'Soltanberdiýewa Orazmuhammet', avatar: '/avatars/61.png', status: 'online' },
    { name: 'Gurbanmuhammedow Jumageldi', avatar: '/avatars/62.png', status: 'offline' },
    { name: 'Täçberdiýewa Hudaýberdi', avatar: '/avatars/63.png', status: 'online' },
    { name: 'Hojamuhammedow Atamyradowa', avatar: '/avatars/64.png', status: 'online' },
    { name: 'Garrymuhammedow Amanmuhammet', avatar: '/avatars/65.png', status: 'online' },
    { name: 'Mämmetgeldiýewa Aýjemal', avatar: '/avatars/66.png', status: 'online' },
    { name: 'Nazarberdiýewa Saparmuhammet', avatar: '/avatars/67.png', status: 'online' },
    { name: 'Gurbanberdiýewa Ogulgerek', avatar: '/avatars/68.png', status: 'online' },
    { name: 'Sarymuhammedow Berdimyrat', avatar: '/avatars/69.png', status: 'online' },
    { name: 'Jumamuhammedow Enejanbibi', avatar: '/avatars/70.png', status: 'online' },
    { name: 'Atamuhammedow Orazmuhammet', avatar: '/avatars/71.png', status: 'online' },
    { name: 'Döwletgeldiýewa Sylapberdi', avatar: '/avatars/72.png', status: 'online' },
    { name: 'Rahmangulyýewa Tavusbibi', avatar: '/avatars/73.png', status: 'online' },
    { name: 'Halmuhammedow Guwançberdi', avatar: '/avatars/74.png', status: 'online' },
    { name: 'Gurbanmuhammedow Hydyrberdi', avatar: '/avatars/75.png', status: 'online' },
    { name: 'Täçmuhammedow Merjenbibi', avatar: '/avatars/76.png', status: 'online' },
    { name: 'Hojamuhammedow Oguljahan', avatar: '/avatars/77.png', status: 'online' },
    { name: 'Garrymuhammedow Amanberdi', avatar: '/avatars/78.png', status: 'online' },
    { name: 'Mämmetgeldiýewa Hudaýberdi', avatar: '/avatars/79.png', status: 'online' },
    { name: 'Nazarberdiýewa Saparmuhammet', avatar: '/avatars/80.png', status: 'online' },
    { name: 'Gurbanberdiýewa Ogulgerek', avatar: '/avatars/81.png', status: 'online' },
    { name: 'Sarymuhammedow Berdimyrat', avatar: '/avatars/82.png', status: 'online' },
    { name: 'Jumamuhammedow Enejanbibi', avatar: '/avatars/83.png', status: 'online' },
    { name: 'Atamuhammedow Orazmuhammet', avatar: '/avatars/84.png', status: 'online' },
    { name: 'Döwletgeldiýewa Sylapberdi', avatar: '/avatars/85.png', status: 'online' },
    { name: 'Rahmangulyýewa Tavusbibi', avatar: '/avatars/86.png', status: 'online' },
    { name: 'Halmuhammedow Guwançberdi', avatar: '/avatars/87.png', status: 'online' },
    { name: 'Gurbanmuhammedow Hydyrberdi', avatar: '/avatars/88.png', status: 'online' },
    { name: 'Täçmuhammedow Merjenbibi', avatar: '/avatars/89.png', status: 'online' },
    { name: 'Hojamuhammedow Oguljahan', avatar: '/avatars/90.png', status: 'online' },
    { name: 'Garrymuhammedow Amanberdi', avatar: '/avatars/91.png', status: 'online' },
    { name: 'Mämmetgeldiýewa Hudaýberdi', avatar: '/avatars/92.png', status: 'online' },
    { name: 'Nazarberdiýewa Saparmuhammet', avatar: '/avatars/93.png', status: 'online' },
    { name: 'Gurbanberdiýewa Ogulgerek', avatar: '/avatars/94.png', status: 'online' },
    { name: 'Sarymuhammedow Berdimyrat', avatar: '/avatars/95.png', status: 'online' },
    { name: 'Jumamuhammedow Enejanbibi', avatar: '/avatars/96.png', status: 'online' },
    { name: 'Atamuhammedow Orazmuhammet', avatar: '/avatars/97.png', status: 'online' },
    { name: 'Döwletgeldiýewa Sylapberdi', avatar: '/avatars/98.png', status: 'online' },
    { name: 'Rahmangulyýewa Tavusbibi', avatar: '/avatars/99.png', status: 'online' },
    { name: 'Halmuhammedow Guwançberdi', avatar: '/avatars/100.png', status: 'online' },
]

export const trunks = [
    {
        id: 'trunk1',
        city: {
            name: 'trunk 1',
            // innerCity: { name: 'Центральный район' },
        },
    },
    {
        id: 'trunk2',
        city: {
            name: 'trunk 2',
            // innerCity: { name: 'Центральный район' },
        },
    },
]
